In [2]:
import pandas as pd
 
# Define a dictionary containing employee data
#export, segments and brands
data = {
        'Brands':['CADBURY BOURNVITA' , 'CADBURY 3-in-1 HOT CHOCOLATE','',''],'Products':['Bournvita' ,'Hot Chocolate','',''],'Exports':['','','',''],'Local':['','','','']
        }
data1 = {
    'Brands':['TOMTOM CLASSIC', 'TOMTOM STRAWBERRY' , 'BUTTERMINT',''],'Products':['Tom Tom', 'Buttermint','',''],
     'Exports':['','','',''],'Local':['','','','']
        }

data2= {
    'Brands':['COCOA POWDER' ,'COCOA BUTTER','',''],
   'Products':['cocoa powder', 'cocoa butter', 'cocoa liquor', 'cocoa cake'],
        'Exports':['cocoa butter', 'cocoa liquor', 'cocoa cake',''],'Local':['cocoa powder','','','']
        }

df= pd.DataFrame(data)
df2 = pd.DataFrame(data1)

df3 = pd.DataFrame(data2)


df4 = pd.concat([df,df2,df3],keys = ['Refreshment Beverages','Confectionery','Intermediate Cocoa Products'] )

df4.to_csv('file/cadbury_market.csv')

df4

                                                     Brands       Products  \
Refreshment Beverages       0             CADBURY BOURNVITA      Bournvita
                            1  CADBURY 3-in-1 HOT CHOCOLATE  Hot Chocolate
                            2
                            3
Confectionery               0                TOMTOM CLASSIC        Tom Tom
                            1             TOMTOM STRAWBERRY     Buttermint
                            2                    BUTTERMINT
                            3
Intermediate Cocoa Products 0                  COCOA POWDER   cocoa powder
                            1                  COCOA BUTTER   cocoa butter
                            2                                 cocoa liquor
                            3                                   cocoa cake

                                    Exports         Local
Refreshment Beverages       0
                            1
                            2
                            3
Confectionery               0
                            1
                            2
                            3
Intermediate Cocoa Products 0  cocoa butter  cocoa powder
                            1  cocoa liquor
                            2    cocoa cake
                            3